server:
  port: 8081
  servlet:
    context-path: /api/users

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tourney?currentSchema=user_schema
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_schema
  flyway:
    default-schema: user_schema
    create-schemas: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.tourney.user_service.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json